void PROGRAMA();

//funciones internas al parser

void FUNCION_INSTRUCCION(), CONJUNVAR(), DECLARACION(), OPERACION_NUM(), TERMINO(), ASIGNACION(), FUN_SUBSTRING(), FUN_CONCAT(),
	FUN_REPLACE(), INS_DO(), INS_CONSOLEWRITE(), INS_CONSOLEREAD(), INS_SWITCH(), CASE(), ABRIR_ARCHIVO(), INS_IF(), INS_WHILE(),
	INS_FOR(), INSTRUCCION(), PAREN_CONDICION(), LLAVE_INSTRUCCION(), DATA_NUM(), DATA_CAD(), ARREGLO(), IDENTIFICADOR(), EXPRESION_ARR(),
	EXPRESION_NUM(), EXPRESION_CAD(), EXPRESION_BOOL(), CONDICION(), COMPAGENERAL(), COMPANUM(), CAD_VAR(), FUNCION(), VARIABLE(),
	TIPO_FILE(), BLOQUE();
//funciones auxiliares del parser
int IS_VARIABLE(),IS_DATA_NUM(),IS_IDENTIFICADOR(),IS_OPERACION_NUM(),
	IS_FUN_SUBSTRING(),IS_FUN_CONCAT(),IS_FUN_REPLACE(),IS_DATA_CAD(),
	IS_EXPRESION_BOOL(),IS_EXPRESION_ARR(),IS_EXPRESION_CAD(),IS_EXPRESION_NUM(),
	IS_COMPANUM(),IS_COMPAGENERAL(),IS_DECLARACION(),IS_FUNCION(),
	IS_FUNCION_INSTRUCCION(),IS_ARREGLO();